# Generated by Django 3.0.8 on 2020-10-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['code']},
        ),
        migrations.AlterField(
            model_name='course',
            name='classroom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
